language: php

php:
    - 7.0
    - 7.1
    - 7.2

matrix:
    fast_finish: true

install: travis_retry composer install --no-interaction --prefer-source

services:
    - mysql
    - postgresql

before_script:
    - travis_retry composer install --prefer-source --no-interaction
    - mysql -u root -e 'CREATE DATABASE test;'
    - psql -c 'create database test;' -U postgres

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
